services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: iker_portfolio
    restart: unless-stopped
    ports:
      - "8084:4321"
    env_file:
      - path: .env.development
        required: false
    volumes:
      - ./src:/app/src
      - ./public:/app/public

  portfolio-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iker_portfolio_prod
    restart: unless-stopped
    ports:
      - "8085:80"
    env_file:
      - path: .env.production
        required: false
    volumes:
      - ./src:/app/src
      - ./public:/app/public
