services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: iker_portfolio
    restart: unless-stopped
    ports:
      - "8020:4321"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./.env.development:/app/.env.development:ro

  portfolio-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iker_portfolio_prod
    restart: unless-stopped
    ports:
      - "8021:80"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./.env.production:/app/.env.production:ro
